apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-deployment
  labels:
    app: ordering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordering
  template:
    metadata:
      labels:
        app: ordering
    spec:
      containers:
      - name: ordering
        image: quay.io/prosenjitjoy/mall-ordering
        ports:
        - name: rest
          containerPort: 8080
        - name: grpc
          containerPort: 9000
        envFrom:
          - configMapRef:
              name: ordering-secret